version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "c:/dockervolumes/minecraftitzg/:/data"
    environment:
      EULA: "TRUE"
    restart: always

volumes:
  mc: {}