version: '3'

services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
      - "c:/dockervolumes/mcbig:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 12G
    image: trueosiris/minecraft-skyfactory4
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "c:/dockervolumes/rcon:/opt/rcon-web-admin/db"

volumes:
  mcbig:
  rcon:
